apiVersion: v1
kind: Service
metadata:
  name: cloudnative-service
spec:
  selector:
    app: cloudnative-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30050
